---
title: "Intervention in augmented reality"
subtitle: "Analysis script for pre-study 2"
author: "Nele Borgert"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE,
                      cache.lazy=FALSE)
```

# Dependencies

```{r}
# package vector
packages <- c("dplyr","psych", "multilevel","MBESS","GPArotation", "tidyr", "ggplot2")

# un-comment to install packages
# for (i in 1:length(packages)){install.packages(packages[i], character.only = T)
# }

# load packages
for (i in 1:length(packages)){
  library(packages[i], character.only = T)
}
```

# Scale evaluation

## SE per item
```{r}
# descriptive
describe(se_data[,-13])
# interpretation
## mean 3-5 (se6, se11, se12 > 5, se9 < 3)
## SD > 1.4 

# item total correlation > 0.3 (se10 < .3)
item.total(se_data[,-13])

# un-comment to plot single histograms
# for (col in 1:12) {
#     hist(se_data[,col])
# }

# plot all
pairs.panels(se_data[,-13], smooth = FALSE, density = FALSE, jiggle = TRUE)
```

## SE total

```{r}
# se mean
describe(se_data[,13])
## original: m = 4.15 (SD = 1.1), skew of g1 = 0.05 and a kurtosis of g2 = −0.06.

# plot histogram
ggplot(data = se_data, aes(x = se_mean)) +
  geom_histogram(bins = 15) +
  xlim(1,7)

# plot density
ggplot(data = se_data, aes(x = se_mean)) +
  geom_density() +
  geom_vline(aes(xintercept=mean(se_mean)), color = "blue", linetype ="dashed", size=1) +
  xlim(1,7)

# omega 
ci.reliability(se_data[,-13], type = 'omega', interval.type = "ml")
omega_se <- se_data[,-13] %>% omegaSem(nfactors = 1)
omega_se
```

## Tested Knowledge per item

```{r}
# descriptive
describe(test_know_data[,-12])
pairs.panels(test_know_data[,-12], smooth = FALSE, density = FALSE, jiggle = TRUE)
# interpretation
## mean 0.15-0.85 (test_know9 < 0.15, test_know2 & test_know3 > 0.85)
## SD > 0.3

# item total correlation > 0 (test_know4, test_know9 < 0; test_know7 = 0.0)
item.total(test_know_data[,-12])
```

## Tested Knowledge total

```{r}
# tested knowledge mean (with all items)
test_know_data$test_know_mean <- as.numeric(test_know_data$test_know_mean) 
describe(test_know_data$test_know_mean)
## m = 0.54 (SD = 0.17), skew of g1 = -0.67 and a kurtosis of g2 = −0.40.
item.total(test_know_data[,-12])

# plot histogram
ggplot(data = test_know_data, aes(x = test_know_mean)) +
  geom_histogram() +
  xlim(0,1)

# plot density
ggplot(data = test_know_data, aes(x = test_know_mean)) +
  geom_density() +
  geom_vline(aes(xintercept=mean(test_know_mean)), color = "blue", linetype ="dashed", size=1) +
  xlim(0,1)

# omega 
fa.parallel(test_know_data[,-12]) # 1 factor/component
ci.reliability(test_know_data[,-12], type = 'omega', interval.type = "ml")
omega_test_know <- test_know_data[,-12] %>% omegaSem(nfactors = 1) # Omega Hierarchical: 0.61 
omega_test_know

#### Include all with omega loadings (gs) above .2 (items 1, 2, 3, 5, 10, 11) ####

fa.parallel(test_know_data[,c(1,2,3,5,10,11)]) # 1 factor/component
ci.reliability(test_know_data[,c(1,2,3,5,10,11)], type = 'omega', interval.type = "ml") # Omega Hierarchical = 0.63
omega_test_know <- test_know_data[,c(1,2,3,5,10,11)] %>% omegaSem(nfactors = 1)
omega_test_know
item.total(test_know_data[,c(1,2,3,5,10,11)])
```

## Perceived Knowledege per item
```{r}
# descriptive
describe(per_know_data[,-3])

# item total correlation 
item.total(per_know_data[,-3]) # not possible?

# un-comment to plot single histograms
 for (col in 1:2) {
     hist(per_know_data[,col])
 }

# plot all
pairs.panels(per_know_data[,-3], smooth = FALSE, density = FALSE, jiggle = TRUE)
```


## Perceived knowledge total

```{r}
# perceived knowledge mean
describe(per_know_data[,3])
## original: m = 2.29 (SD = 0.73), skew of g1 = 0.28 and a kurtosis of g2 = −0.19.

# plot histogram
ggplot(data = per_know_data, aes(x = per_know_mean)) +
  geom_histogram(bins = 15) +
  xlim(1,5)

# plot density
ggplot(data = per_know_data, aes(x = per_know_mean)) +
  geom_density() +
  geom_vline(aes(xintercept=mean(per_know_mean)), color = "blue", linetype ="dashed", size=1) +
  xlim(1,5)

# omega: not possible?
ci.reliability(per_know_data[,-3], type = 'omega', interval.type = "ml")
# omega_se <- per_know_data[,-3] %>% omegaSem(nfactors = 1)
# omega_se
```